### PR TITLE
changed LOGGED_IN_HEURISTIC

### PR DESCRIPTION
**Pull request by Protonex**
… to the untranslated string for internationalized maps interface versions.

### CODE REVIEW

**Comment by costastf** [comment]
The message I had as a heuristic for log in status is the message retrieved after the service successfully logs in on the url I have hard coded in the code which defaults to en language. Did you end up in a situation where after following the log in procedure without touching the URL you ended up with that message instead? If that is the case then we need to make the heuristic a list and check for any of them.

**Comment by Protonex** [comment]
My default account locale is 'ru', so login procedure was trapped in the check-loop
`            while LOGGED_IN_HEURISTIC not in driver.page_source:
                sleep(0.5)
`
It cannot find any occurrences of the original text.

Besides of it, i switched language to en (by adding 'https://www.google.com/maps?hl=en' and cannot find original text also!
The string that i provided present in both locales of maps, so i decided to make pull request...
But now i checked other locales. This text (in meta tags) does not present in other locales sources.

So maybe better to change also (in addition to this pull request) a redirect URL to a en-locale version:
`
MAPS_LOGIN = ('https://accounts.google.com/signin/v2/identifier?'
              'hl=en&'
              'passive=true&'
              'continue=https%3A%2F%2Fwww.google.com%2Fmaps%2F%4040.7484986%2C-73.9857129%2C15z&'
              'service=local&'
              'flowName=GlifWebSignIn&'
              'flowEntry=ServiceLogin')
`

to

MAPS_LOGIN = ('https://accounts.google.com/signin/v2/identifier?'
              'hl=en&'
              'passive=true&'
              'continue=https%3A%2F%2Fwww.google.com%2Fmaps%2F%4040.7484986%2C-73.9857129%2C15z%3Fhl%3Den&'
              'service=local&'
              'flowName=GlifWebSignIn&'
              'flowEntry=ServiceLogin')

Just checked and it works well.

**Comment by costastf** [comment]
Hi, sorry i can't spot the difference between what is there and what you suggest we change too. Do you mind putting that in the PR so I can make sense of it?

**Comment by lolomin** [comment]
Hi,

Just tried to make your mapscookiegettercli working and , as I'm French, faced the same problem as Protonex is reporting.

@costastf : if you check the MAPS_LOGIN provided by Protonex, we can see a new string added here : "%3Fhl%3Den" just after %2C15z. This is probably this string that make the process to success everytime for every locales, like Protonex is saying !?

I did not test it by myself as to make the whole process working, I've finally replaced the hard coded string to the one translated in French and this made it working, but I have still an interrogation then with the real usage/usability of this project : I was using your locationsharinglib v3.0.11 and this one suddenly stopped working a few days ago probably because Google made some modifications somewhere in the login process and so the cookies file cannot be automatically grabbed anymore like before it was ...
so then with this project I have something working to grab the cookie file but I need to do the process by hand/manually everytime, is there a way to automate it with a headless firefox or something like that please ?

Thanks a lot for your time and your code, I'm not a python dev and not having any knowledge to python otherwise I would have already tried to debug what is not working anymore with the current version I'm using :/ 

Regards,

lolomin

**Comment by costastf** [comment]
I have changed the code with all points mentioned and mentioned @Protonex as a contributor. Thank you guys!

**Pull request closed without merging**
